### ISSUE TITLE
Consider another hosting service for this project

### ISSUE THREAD

**Issue by Atavic** [crazy-max/WindowsSpyBlocker#113]
Will MS change Github?
Will MS put ads here?
Will MS hunt the repos they consider *unfriendly* to them?

While in doubt, consider something like Gitlab as an hosting alternative.

**Comment by Atavic** [comment]
Self hosting is a plus. I'm just giving hints here. Related discussion focused on Sourceforge vs Gitlab: https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/65#issuecomment-394876579

**Comment by Atavic** [comment]
More options [here](https://git.wiki.kernel.org/index.php/GitHosting) and [here](https://github.com/bderiso/Microsoft-Github-acquisition/wiki/GitHub-Alternatives).

**Comment by crazy-max** [comment]
_"Trust takes years to build, seconds to break, and forever to repair."_

As a developer I am very sceptical about the future of GitHub. Here are a few points that might worry me in the future :

* Read role on private repo for Microsoft employees ? [Response of Nat Friedman](https://old.reddit.com/r/AMA/comments/8pc8mf/im_nat_friedman_future_ceo_of_github_ama/e0a27m7/)
* UI clutter changes. Strong link with LinkedIn?

Some people will take longer for sure, but immediately assuming a product is ruined because Microsoft bought it is a tad much in my opinion. If Microsoft starts making changes I don't like, then I will be moving my repos to a different service, but until then I'm not worried about the platform.

For me it doesn't make sense to move right away if you're using GitHub's free services and open source your code. And it's even more ironic with this repo ;) But for a competitive company it can be the other way around.

Microsoft had to earn the trust by fundamentally changing their views and actions twords OSS, Linux, etc... And the deal won't close until the end of the year. So for the moment I'm still paying attention and preparing the transition just in case.

If you want to know more about the transition / future CEO @natfriedman, i suggest to read [this AMA](https://www.reddit.com/r/AMA/comments/8pc8mf/im_nat_friedman_future_ceo_of_github_ama/).
