### ISSUE TITLE
Are Windows hosts entries effective at all?

### ISSUE THREAD

**Issue by dimqua** [crazy-max/WindowsSpyBlocker#117]
According [to Tron Script author](https://github.com/bmrf/tron/blob/master/resources/stage_4_repair/disable_windows_telemetry/purge_windows_10_telemetry.bat#L478):

> Windows maliciously ignores any rules blocking access to telemetry servers. Currently the only known solution is installing null-routes in the route table.

Is it true statement or not?

**Comment by dnmTX** [comment]
@dimqua  i've heard about that too,that any telemetry domains even if they are blocked in hosts file still going trough.Luckily i was able to load custom firmware on my router which has dnsmasq in it so that's where my hosts files are and it's working.I simply tested this link:
https://support.microsoft.com/en-us/help/4000825/windows-10-windows-server-2016-update-history
....aaand this(check the screenshot out) is from Chrome Web Tools showing me the good news 😉 
![wintelemetry](https://user-images.githubusercontent.com/34774426/43811475-43934582-9a82-11e8-8c79-23f63a89f23d.PNG)

**Comment by dimqua** [comment]
@dnmTX I use DNS-based method too, but by using [dnscrypt-proxy](http://dnscrypt.info/). It's probably better than dnsmasq for domain blocking, since it supports regex and wildcard rules, as well as the latest version of [pi-hole](https://pi-hole.net/).

**Comment by dnmTX** [comment]
@dimqua  wildcards sounds like a dream come true but in the present most of the lists provided here in GitHub or Gitlab doesn't offer that option.Pi-hole is using dnsmasq as a dns resolver.My router is old so having dnsmasq in it is a big improvement on my end and again,it doesn't slow down browsing even a bit.If i get a better router in the feature will look for more advanced dns resolver.Having the resolver installed anywhere but on my Windows system makes me sleep better every night.

**Comment by dimqua** [comment]
The latest version of PiHole uses FTLDNS, their own fork of dnsmasq which supports Regex.

**Comment by dnmTX** [comment]
Oh.....i see,well i guess i'm behind on the latest news :-)

**Comment by crazy-max** [comment]
@dimqua It's strongly recommended to use a dedicated firewall, dns server as some hosts are hardcoded (eg. `dnsapi.dll`)
