### ISSUE TITLE
IPv6 addresses aren't blocked

### ISSUE THREAD

**Issue by Jookia** [crazy-max/WindowsSpyBlocker#146]
At the moment any (hypothetical?) hardcoded IPv6 addresses will pass the filter completely.

**Comment by Atavic** [comment]
Related to: https://github.com/crazy-max/WindowsSpyBlocker/issues/95

**Comment by crazy-max** [comment]
As @Atavic said it's related to #95, I will check IPv6 domain readiness and add them.

**Comment by dnmTX** [comment]
@crazy-max adding IPv6 rules is not a bad idea i just hope that you'll do separate lists for it as some of us don't even use IPv6. Personally,on my end,it's disabled.
Also regarding one of the [comments](https://github.com/crazy-max/WindowsSpyBlocker/issues/95#issuecomment-359173972) in #95,simple `::` will do,instead of `0:0:0:0:0:0:0:0`,which is the compressed version of it.

**Comment by crazy-max** [comment]
IPv6 blocking for hosts are available : [data/hosts/[extra|spy|update]_v6.txt](https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/hosts)

**Comment by dnmTX** [comment]
@crazy-max thanks for not mixing them up.
Appreciated 👍

**Comment by crazy-max** [comment]
@dnmTX You're welcome ;)
