### ISSUE TITLE
You closed my tickets without solution?

### ISSUE THREAD

**Issue by leeuwtjex** [crazy-max/WindowsSpyBlocker#159]
Max, this totally sucks.

This is a bug report for the issue support here.

I had 2 tickets which you closed without an accepted solution?
Isn't is the users job to close a ticket when an issue is solved?

I CAN'T GO BACK TO MY WIN 7 DEFAULT NSCI settings.
I gave you all details, put time in it to report, it is gone now.
The other ticket where I took time to ask reasonable questions is destroyed.

So,  I suppose I need to sort out myself what the original settings where for:
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet]
?

Great Work! Big thanks.

**Comment by crazy-max** [comment]
I closed following your message that it was a problem on your side... And by looking at the change history of your message, you edited it after I closed it :

![image](https://user-images.githubusercontent.com/1951866/62740604-91e2b700-ba38-11e9-953e-5bdf6a454400.png)

So you're the only one to blame here. The reg file I attached to you in issue #158 comes from a fresh Windows 7 installation.

Concerning the other ticket I closed it because I answered ALL your questions. Even if the ticket is closed you can still answer it but I think rather that given the tone you use I see closing this ticket and let you find other alternatives to WindowsSpyBlocker where you will probably have better support...
