### ISSUE TITLE
MSN Blocked

### ISSUE THREAD

**Issue by share3141** [crazy-max/WindowsSpyBlocker#16]
#### Please first
* Read the FAQ : https://github.com/crazy-max/WindowsSpyBlocker/wiki/FAQ
* Search for existing issues : https://github.com/crazy-max/WindowsSpyBlocker/issues

#### Steps to reproduce this issue
1.
2.
3.

#### Expected Behaviour
Tell me what should happen

#### Actual Behaviour
Tell me what happens instead

#### Configuration

**Country (ex. United-States)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

```
Open a command prompt and type winver then
take / save the screenshot of the window and
drag the image file in this issue.
For example: https://goo.gl/03d7gI
```

**Comment by share3141** [comment]
I am sorry if this is the wrong way to ask  you something.  I have never used GitHub.  I have an issue that when I apply your spy rules for Windows 10 I can no longer access MSN.  How do I figure out how to allow that site through?  Also - when I run the firewall.bat file I have the opportunity to add either local or remote rules.  What is the difference?  They appear to be the same rules.  Thank you.

**Comment by crazy-max** [comment]
Hi,

The difference between local and remote is up to you.
Remote take the rules directly from github
Local take the rules from local file

Can you edit your issue and fill the blank.
Take [the issue 15](https://github.com/crazy-max/WindowsSpyBlocker/issues/15) for example.

Then for your issue, there's maybe a problem with some hosts and/or firewall rules that need to be updated :
* First remove all WindowsSpyBlocker firewall rules (with firewall.bat script) and check again.
* Otherwise remove WindowsSpyBlocker hosts and check again.
* Otherwise there is a problem with your ISP !

Thanks.

**Comment by share3141** [comment]
This is the firewall rule that is causing me to not be able to get 
MSN.com on Cox. 204.79.197.197-204.79.197.214. I'll see if I can narrow 
it down

**Comment by share3141** [comment]
appears to be 204.79.197.203

**Comment by crazy-max** [comment]
Ok i will investigate on it
