### ISSUE TITLE
How to automate with ESET?

### ISSUE THREAD

**Issue by jeffshead** [crazy-max/WindowsSpyBlocker#201]
1. I did not find the instructions on how to automate. Is there no automation? Does the block list have to be applied to ESET, manually, after every update?
2. Does the stand-alone WSB exe get it's updated block list from github or the PC it's running on?
3. How effective is blocking IP's in the first place? If Windows requires a reboot after a Windows update is applied, can't the firewall and HOSTS file be bypassed by the telemetry components?

**Comment by crazy-max** [comment]
@jeffshead 

> I did not find the instructions on how to automate. Is there no automation? Does the block list have to be applied to ESET, manually, after every update?

Looking at the [official documentation](https://help.eset.com/eis/13/en-US/?idh_dialog_epfw_rule_create_general.html), it doesn't seem feasible.

> Does the stand-alone WSB exe get it's updated block list from github or the PC it's running on?

Rules are embedded in the executable to provide offline update. You can extract these rules by opening WindowsSpyBlocker and going to `Dev` menu and `Extract data`.

> How effective is blocking IP's in the first place? If Windows requires a reboot after a Windows update is applied, can't the firewall and HOSTS file be bypassed by the telemetry components?

I think ESET Firewall works through a dedicated virtual network adapter so everything "should be" block correctly. As far as blocking via hard-coding in dll `dnsapi.dll` is concerned, I had already mentioned this before and that's why I had advised to use either one's own router as a firewall or tools like pi-hole.
