### ISSUE TITLE
activity.windows.com

### ISSUE THREAD

**Issue by beerisgood** [crazy-max/WindowsSpyBlocker#205]
**activity.windows.com** is a false positive.

If blocked, no comment votes are possible in Windows Store.

**Comment by beerisgood** [comment]
@crazy-max

**Comment by crazy-max** [comment]
Stop spamming

**Comment by crazy-max** [comment]
@beerisgood 

Like #206, this domain has been detected on a healthy system with Windows Stores disabled.

During January 2020, this endpoint has been called **681 times** (detected 622 through wireshark/qemu, 30 through sysmon and 29 through proxifier) so I don't think this is a legitimate/user input call.

If this impinges on the use of Windows Stores, I suggest you whitelist it in your DNS configuration.

**Comment by SeriousHoax** [comment]
@crazy-max This domain along with the corresponding ip `52.157.234.37` should be whitelisted because with this blocked the new Chromium Edge browser's sync feature doesn't work. Sync is relied on it. Since it's becoming the main built in browser and already many people are using it, this domain needs to be whitelisted.
