### ISSUE TITLE
Can't contact update server

### ISSUE THREAD

**Issue by pseudohero** [crazy-max/WindowsSpyBlocker#250]
`WindowsSpyBlocker can't contact the update server: Get https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/.res/latest: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

I also get a web request error on IPV4 and IPV6 when testing NCSI on both WSB rules and the Microsoft rules. (DNS is fine for both, though.)

**Comment by ubergeek77** [comment]
I can confirm this. I think Pastebin is having issues at the moment. Trying to go to any `raw` page on Pastebin causes it to `301` redirect loop until the request client gives up.

This is an issue, because WindowsSpyBlocker tries to connect to the following in order to test IPv4 and IPv6 connections:

`https://pastebin.com/raw/84qBci10`

You can still go to the non-plaintext page in a browser by omitting `raw` in the URL, but that obviously won't work for this situation.

The short term solution would be to wait for Pastebin to fix their webserver issues, but there's no telling how long that will take (and this could happen again in the future).

A long-term, future-proof solution that @crazy-max might want to consider is putting a permanent text file in this repository, then have WindowsSpyBlocker set the `ActiveWebProbe` to point to that file.

For instance, a file named `probe` could be placed in the root of this repository, with the text content of:

`WindowsSpyBlocker`

Then, the `ActiveWebProbe` values could be changed from the current values:

https://github.com/crazy-max/WindowsSpyBlocker/blob/dd3400498fca9688a61ef6d3a45f634a31d0d865/app/settings.json#L119-L125

To these new values:

```
      "wsb": {
        "webHostV4": "raw.githubusercontent.com",
        "webPathV4": "crazy-max/WindowsSpyBlocker/master/probe",
        "webContentV4": "WindowsSpyBlocker",
        "webHostV6": "raw.githubusercontent.com",
        "webPathV6": "crazy-max/WindowsSpyBlocker/master/probe",
        "webContentV6": "WindowsSpyBlocker",
```

This way, WindowsSpyBlocker's active check no longer relies on Pastebin, and instead relies on GitHub, which is bound to be much more reliable (this project is hosted here, after all!)

**Comment by crazy-max** [comment]
@ubergeek77 

> A long-term, future-proof solution that @crazy-max might want to consider is putting a permanent text file in this repository, then have WindowsSpyBlocker set the ActiveWebProbe to point to that file.

Unfortunately, we can't. NCSI probe only supports http, not https. And GitHub is https only.

**Comment by ubergeek77** [comment]
Ah, I didn't know NCSI had that limitation.

In any case, it seems Pastebin has sorted out the issue on their end. Pastebin `raw` URLs are working again as of now.

Still, this whole thing does make me wonder if there are any other non-Microsoft, "permanent" HTTP pages. I'll keep an eye out for one in case this happens to Pastebin again.

**Comment by pseudohero** [comment]
Thanks for the updates folks. I’ll admit I’m not near as savvy as you both in regards to this, but this is the second or third time I’ve experienced this issue over a 6 or so month period. I realise this is not your fault and it seems like it is usually rectified within a day or so, but it does seem like “self-hosting” this doc somewhere else could be beneficial.

I will mark topic as closed.
