### ISSUE TITLE
Option to whitelist Microsoft Edge Addons page

### ISSUE THREAD

**Issue by hl2guide** [crazy-max/WindowsSpyBlocker#308]
#### Steps to reproduce this issue

1. try to open the address: https://microsoftedge.microsoft.com/addons

#### Expected behaviour

> An option to whitelist the Microsoft Edge Addons page.

#### Actual behaviour

> Page is blocked.

### Rules used

> (ex: `data/firewall/spy.txt`)

1. Spy rules

### Configuration

**Country (ex. United-States)** :
Australia

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro 20H2 (OS Build 19042.746)
**Winver screenshot** :
![1](https://user-images.githubusercontent.com/17044982/105817078-40056680-6009-11eb-85eb-9b94351fcb21.JPG)

**Comment by dnmTX** [comment]
Dean @hl2guide  the IP associated with `microsoftedge.microsoft.com` is **13.107.6.158** which is only present in 
[data/firewall/extra.txt](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/firewall/extra.txt) which is not recommended for use to the majority here due to high amount of false-positives.
You either need to...really switch to `data/firewall/spy.txt` or just remove the aforementioned IP on your end.

**Comment by hl2guide** [comment]
ah ok, oops 🙄 my bad

**Comment by matin417** [comment]
😏😏🤔🤔

ในวันที่ จ. 25 ม.ค. 2021 เวลา 22:31 Dean <notifications@github.com>
เขียนว่า:
