### ISSUE TITLE
WSP blocks Yahoo images

### ISSUE THREAD

**Issue by daveimagery** [crazy-max/WindowsSpyBlocker#60]
Hi, thank you for the continued development of WSP.  With latest version, I notice it prevents Yahoo images from pulling up results.  When I revert WSP, images appear.  Can this be fixed?  Thank you :)

**Comment by crazy-max** [comment]
Hi, what is your operating system? What kind of rules (hosts? firewall? /  extra? spy? update?)
Can you send a link of an image?
Thanks for your contrib

**Comment by daveimagery** [comment]
Hi,  Win10 64Bit.  I just did the default IP address block in your program.  It's not one particular image.  When you go to Yahoo images, and do a search, no results come back, they are just blank boxes.  This is not unique to your program, I have noticed it with other anti spy software.  The IP range for Yahoo images, must be very close to known Microsoft spying IP's.  Thanks

**Comment by crazy-max** [comment]
"Default IP" ?

**Comment by crazy-max** [comment]
>I just did the default IP address block in your program

Can you be more precise? Does that concern the firewall rules? hosts?
And for what type? extra? spy? update?
Thanks

**Comment by daveimagery** [comment]
Hi, I believe it's in the firewall rules, and I did the spy procedure.  I have experienced this before, it is usually only one or two ip addresses.  In other programs, I would just go into firewall, and disable/enable rules one by one to determine which it was, but now there are so many.  Would take far too long imo.

**Comment by crazy-max** [comment]
Ok i've checked for Windows 10 the firewall spy rules and i don't have any issue on yahoo images but may be this concerns an other subdomain linked to your country.
Can you send a link of an image with a blank box please ?

**Comment by daveimagery** [comment]
Okay this time the problem didn't occur for me just applying the Spy rules.  It wasn't until I selected your "Extra" rules, did I notice it again.  This time some of the images appear, but then still some appear as white boxes.  As you can see here.  http://imgur.com/a/jmDHq

The search I did --> http://tinyurl.com/ydfnwkox

Link to white box ---> http://tinyurl.com/y83mns29

**Comment by crazy-max** [comment]
This concerns the following ip range in win10 firewall extra rules : `204.79.197.0-204.79.197.255`

As you can see in the following screenshot, you have blank image because the domains `tse*.mm.bing.net` are part of this ip range :

![image](https://cloud.githubusercontent.com/assets/1951866/26521652/d5cec2de-42ed-11e7-8c16-8913fac99d27.png)

Be careful with extra rules, they are to be applied in case of real necessity and be used to block third party applications. And here Yahoo seems to use a Microsoft cache domain (Bing CDN).

More info : https://www.threatcrowd.org/domain.php?domain=tse3.mm.bing.net

In your case i suggest to disable the extra rules for now.

**Comment by daveimagery** [comment]
Makes sense, thank you for following up.  I will apply just the Spy rules.
